import type { Metadata } from "next";
// import localFont from "next/font/local";
import "./globals.css";
import { SidebarProvider, SidebarTrigger } from "@/components/ui/sidebar";
import  SideBar  from "../components/SideBar";
import { usePathname } from "next/navigation";

// const geistSans = localFont({
//   src: "./fonts/GeistVF.woff",
//   variable: "--font-geist-sans",
//   weight: "100 900",
// });
// const geistMono = localFont({
//   src: "./fonts/GeistMonoVF.woff",
//   variable: "--font-geist-mono",
//   weight: "100 900",
// });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const pathname = usePathname();

  // Check if the current path is the landing page
  const isLandingPage = pathname === "/";

  return (
    <html lang="en">
      <body className="antialiased">
        <SidebarProvider>
          {/* Conditionally render the AppSidebar for all pages except the landing page */}
          {!isLandingPage && <SideBar />}
          <main className={!isLandingPage ? "ml-64" : ""}>
            {/* Conditionally render the SidebarTrigger */}
            {!isLandingPage && <SidebarTrigger />}
            {children}
          </main>
        </SidebarProvider>
      </body>
    </html>
  );
}
